apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - name: httpd
    image: macfly4200.8gears.ch/library/httpd
    imagePullPolicy: Always
